In [13]:
# function output the first row -> end column -> end row -> first column
# output a row or a column and delete it
import numpy as np
output = []
def func_output(array, k):
    if k == 0:
        output.extend(list(array[0,:]))
        array = np.delete(array, 0, 0)
    elif k == 1:
        output.extend(list(array[:,-1]))
        array = np.delete(array, -1, 1)
    elif k == 2:
        output.extend(reversed(list(array[-1,:])))
        array = np.delete(array, -1, 0)
    else:
        output.extend(reversed(list(array[:,0])))
        array = np.delete(array, 0, 1)
    return array

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
k = 0
while arr.size:
    k = k % 4
    arr = func_output(arr, k)
    k = k+1
else :
    print output

[1, 2, 3, 4, 8, 12, 11, 10, 9, 5, 6, 7]


In [16]:
class queue:
    def __init__(self):
        self.list = []
        
    def push(self, element):
        self.list.append(element)
    
    def pop(self):
        print self.list[0]
        del self.list[0]
    
    def top(self):
        print self.list[0]
        
q = queue()
q.push(1)
q.pop()
q.push(2)
q.push(3)
q.top()
q.pop()

1
2
2


In [33]:
import numpy as np
# B = np.array([])
def sum(A):
    B = A.copy()
    for i in range(0,int(A.shape[0])):
        for j in range(0,int(A.shape[1])):
            B[i][j] = np.sum(A[:i+1, :j+1])
    print B
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
sum(arr)

[[ 1  3  6 10]
 [ 6 14 24 36]
 [15 33 54 78]]


In [5]:
class ListNode(object):
    def __init__(self, val, next = None):
        self.val = val
        self.next = next
        
def display_list(head):
    vals = []
    while head:
        vals.append(str(head.val))
        head = head.next
    else:
        print '->'.join(vals)
        
def reverse(head):
    new_head = None
    while head:
        node = head
        head = head.next
        node.next = new_head
        new_head = node
    return new_head        
l_5 = ListNode(5)
l_4 = ListNode(4, l_5)
l_3 = ListNode(3, l_4)
l_2 = ListNode(2, l_3)
l_1 = ListNode(1, l_2)
display_list(l_1)

1->2->3->4->5


In [7]:
import traceback
class Screen(object):
    
    @property
    def width(self):
        return self._width
    
    @width.setter
    def width(self, width):
        if isinstance(width, basestring):
            raise ValueError('width can not be string!')
        self._width = width
        
    @property
    def height(self):
        return self._height
    
    @width.setter
    def height(self, height):
        if isinstance(height, basestring):
            raise ValueError('height can not be string!')
        self._height = height
        
    @property
    def resolution(self):
        self._resolution = self._width * self._height
        return self._resolution

s = Screen()
s.width = 75
s.height = 20
print s.resolution
try:
    s.width = 'abc'
except ValueError:
    traceback.print_exc()
try:
    s.resolution = 1500
except AttributeError:
    traceback.print_exc()

1500


Traceback (most recent call last):
  File "<ipython-input-7-87354f2b7f7f>", line 34, in <module>
    s.width = 'abc'
  File "<ipython-input-7-87354f2b7f7f>", line 11, in width
    raise ValueError('width can not be string!')
ValueError: width can not be string!
Traceback (most recent call last):
  File "<ipython-input-7-87354f2b7f7f>", line 38, in <module>
    s.resolution = 1500
AttributeError: can't set attribute


In [ ]:
class Prime(object):
    def __init__(self, value):
        self.value = 0
        
    def __iter__(self):
        return self
    
    def next(self):
        self.value = self.value + 1
        if self.value > 100: 
            raise StopIteration()
        #= [self.value for i in range(2, self.value) if (self.value % i) != 0]
        if not [j for j in range(2,self.value) if self.value%j ==0]:
            return self.value
        
    def __getitem__(self, n):
        if isinstance(n, int):
            if not [j for j in range(2,n) if n%j ==0]:
                return n
            else:
                print '%d in not prime number' % n
        if isinstance(n, slice):
            start = n.start
            stop = n.stop
            L = []
            for x in range(stop):
                if x >= start:
                    if not [j for j in range(2,x) if x%j ==0]:
                        L.append(x)
            return L

for value in Prime():
    print value
    
